---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: install elasticsearch role
    shell: ansible-galaxy install elastic.elasticsearch
    
  - name: copy J2
    template:
      src: es.yml.j2
      dest: es.yml
      owner: root
      mode: "u=rw,g=r,o=r"
      
  - name: install elasticsearch in node
    shell: ansible-playbook es.yml -i /etc/ansible/elasticsearch-master.hosts  --extra-vars "@extra-vars.json" >> /tmp/es.logs
    
  - name: install elasticsearch in node
    shell: ansible-playbook installplugin.yml -i /etc/ansible/elasticsearch-master.hosts
